---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: glusterfs-csi-pv
  annotations:
    csi.gluster/allocation: "192.168.100.59:1073741824,192.168.100.241:1073741824"
spec:
  storageClassName: glusterfs-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
